In [1]:
import pandas as pd
from sklearn import linear_model,ensemble
import numpy as np

In [2]:
df = pd.read_csv("/home/hr/Desktop/dmpa_proj/dataset/train.csv")
df.head()
test_set = pd.read_csv("/home/hr/Desktop/dmpa_proj/dataset/test.csv")
#test_set.head()

In [3]:
def preprocess(df):
    df = df.select_dtypes(np.number)
    df = df.dropna()   #Drop missing values rows
    return df
df = preprocess(df)
#test_set = preprocess(test_set)
test_set = test_set.select_dtypes(np.number)

In [ ]:
def get_X(df):
    df = df[df.columns[df.columns!='SalePrice']]
    df = df[df.columns[df.columns!='Id']]
    print df.shape
    return df
def get_Y(df):
    return df["SalePrice"]

def get_missing_substituted_value(df):
    df = df[df.columns[df.columns!='SalePrice']]
    df = df[df.columns[df.columns!='Id']]
    for i in df:
        df[i] = df[i].fillna(value = df[i].median())
    print df.shape
    return df

reg = ensemble.GradientBoostingClassifier()
X_train = get_X(df)
Y_train = get_Y(df)
X_test = get_missing_substituted_value(test_set)

X_test.head()

(1121, 36)
(1459, 36)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,470.0,360,36,0,0,0,0,0,6,2010
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,506.0,0,82,0,0,144,0,0,1,2010

In [ ]:
reg.fit(X_train,Y_train)

In [ ]:
ans = reg.predict(X_test)
ans = pd.DataFrame(ans)
ans.plot(kind="hist").show()

In [ ]:
f = open("/home/hr/Desktop/dmpa_proj/dataset/sub2.csv","w+")
for i in range(1459):
    print i
    f.write("{0},{1}\n".format(i+1461,ans[i]))